// backend/src/main/java/com/realestate/duediligence/service/impl/ReportSectionBuilder.java
package com.realestate.duediligence.service.impl;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.realestate.duediligence.aggregation.AggregatedPropertyResponse;
import com.realestate.duediligence.dto.RiskBreakdownDto;
import com.realestate.duediligence.entity.DueDiligenceReport;
import com.realestate.duediligence.entity.ReportSection;
import com.realestate.duediligence.entity.RiskAssessment;
import com.realestate.duediligence.integration.common.IntegrationResponse;

import lombok.RequiredArgsConstructor;

/**
 * Builds the 8 sections of a due diligence report.
 *
 * Separated from the async executor so it can be unit-tested in isolation
 * and reused by future features (PDF export, email digests, etc.)
 *
 * Sections built in this order:
 *   COVER → EXECUTIVE_SUMMARY → PROPERTY_OVERVIEW → RISK_ANALYSIS →
 *   COMPARABLE → FINANCIAL → RECOMMENDATIONS → APPENDIX
 */
@Component
@RequiredArgsConstructor
public class ReportSectionBuilder {

    private static final Logger log = LoggerFactory.getLogger(ReportSectionBuilder.class);
    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("MMMM d, yyyy 'at' HH:mm 'UTC'");

    private final ObjectMapper objectMapper;

    /** Builds all 8 sections in display order. */
    public List<ReportSection> buildAll(DueDiligenceReport report,
                                        AggregatedPropertyResponse agg,
                                        RiskAssessment assessment,
                                        RiskBreakdownDto breakdown) {
        List<ReportSection> sections = new ArrayList<>();
        int order = 0;
        sections.add(buildCover(report, agg, order++));
        sections.add(buildExecutiveSummary(report, assessment, breakdown, order++));
        sections.add(buildPropertyOverview(report, agg, order++));
        sections.add(buildRiskAnalysis(report, breakdown, order++));
        sections.add(buildComparable(report, order++));
        sections.add(buildFinancial(report, agg, order++));
        sections.add(buildRecommendations(report, breakdown, order++));
        sections.add(buildAppendix(report, agg, order++));
        return sections;
    }

    // ── COVER ─────────────────────────────────────────────────────

    private ReportSection buildCover(DueDiligenceReport report,
                                     AggregatedPropertyResponse agg, int order) {
        var prop = agg.getProperty();
        StringBuilder content = new StringBuilder();
        content.append("Due Diligence Report\n");
        content.append("====================\n\n");
        if (prop != null) {
            content.append("Property: ").append(nvl(prop.getAddress())).append("\n");
            if (prop.getCity() != null) {
                content.append("Location: ").append(prop.getCity());
                if (prop.getState() != null) content.append(", ").append(prop.getState());
                if (prop.getZipCode() != null) content.append(" ").append(prop.getZipCode());
                content.append("\n");
            }
            if (prop.getPropertyType() != null) {
                content.append("Property Type: ").append(prop.getPropertyType()).append("\n");
            }
        }
        content.append("\nGenerated by: ")
                .append(report.getGeneratedBy() != null ? report.getGeneratedBy().getEmail() : "unknown")
                .append("\n");
        content.append("Report Version: ").append(report.getVersion()).append("\n");
        content.append("Generated: ").append(LocalDateTime.now().format(DATE_FMT)).append("\n");
        content.append("\nReport ID: ").append(report.getId()).append("\n");

        return section(report, "COVER", "Cover Page", order,
                content.toString(), toJson(prop));
    }

    // ── EXECUTIVE_SUMMARY ─────────────────────────────────────────

    private ReportSection buildExecutiveSummary(DueDiligenceReport report,
                                                RiskAssessment assessment,
                                                RiskBreakdownDto breakdown, int order) {
        StringBuilder content = new StringBuilder();
        content.append("Executive Summary\n");
        content.append("=================\n\n");
        content.append(nvl(assessment.getSummary())).append("\n\n");
        content.append("Overall Risk Score: ")
                .append(String.format("%.1f", nvl(assessment.getOverallScore())))
                .append(" / 100 — ").append(assessment.getOverallLevel().name()).append("\n\n");

        content.append("Category Scores:\n");
        content.append(String.format("  * Flood:         %5.1f  (%s)%n",
                nvl(assessment.getFloodScore()), levelForScore(assessment.getFloodScore())));
        content.append(String.format("  * Legal:         %5.1f  (%s)%n",
                nvl(assessment.getLegalScore()), levelForScore(assessment.getLegalScore())));
        content.append(String.format("  * Tax:           %5.1f  (%s)%n",
                nvl(assessment.getTaxScore()), levelForScore(assessment.getTaxScore())));
        content.append(String.format("  * Zoning:        %5.1f  (%s)%n",
                nvl(assessment.getZoningScore()), levelForScore(assessment.getZoningScore())));
        content.append(String.format("  * Environmental: %5.1f  (%s)%n",
                nvl(assessment.getEnvironmentalScore()), levelForScore(assessment.getEnvironmentalScore())));
        content.append(String.format("  * Market:        %5.1f  (%s)%n",
                nvl(assessment.getMarketScore()), levelForScore(assessment.getMarketScore())));

        if (breakdown.isDataIncomplete()) {
            content.append("\nData Quality Notice: ")
                    .append(breakdown.getUnavailableProviderCount())
                    .append(" data source(s) were unavailable at generation time. ")
                    .append("Scores reflect conservative estimates for missing data.\n");
        }

        return section(report, "EXECUTIVE_SUMMARY", "Executive Summary", order,
                content.toString(), toJson(breakdown));
    }

    // ── PROPERTY_OVERVIEW ─────────────────────────────────────────

    private ReportSection buildPropertyOverview(DueDiligenceReport report,
                                                AggregatedPropertyResponse agg, int order) {
        var prop = agg.getProperty();
        StringBuilder content = new StringBuilder();
        content.append("Property Overview\n");
        content.append("=================\n\n");
        if (prop != null) {
            content.append("Address:       ").append(nvl(prop.getAddress())).append("\n");
            if (prop.getCity() != null)         content.append("City:          ").append(prop.getCity()).append("\n");
            if (prop.getState() != null)        content.append("State:         ").append(prop.getState()).append("\n");
            if (prop.getZipCode() != null)      content.append("ZIP:           ").append(prop.getZipCode()).append("\n");
            if (prop.getPropertyType() != null) content.append("Type:          ").append(prop.getPropertyType()).append("\n");
            if (prop.getArea() != null)         content.append(String.format("Area:          %.0f sq ft%n", prop.getArea()));
            if (prop.getLotSize() != null)      content.append(String.format("Lot Size:      %.0f sq ft%n", prop.getLotSize()));
            if (prop.getYearBuilt() != null)    content.append("Year Built:    ").append(prop.getYearBuilt()).append("\n");
            if (prop.getBedrooms() != null)     content.append("Bedrooms:      ").append(prop.getBedrooms()).append("\n");
            if (prop.getBathrooms() != null)    content.append("Bathrooms:     ").append(prop.getBathrooms()).append("\n");
            if (prop.getStories() != null)      content.append("Stories:       ").append(prop.getStories()).append("\n");
            if (prop.getStructureType() != null) content.append("Structure:     ").append(prop.getStructureType()).append("\n");
            if (prop.getCondition() != null)    content.append("Condition:     ").append(prop.getCondition()).append("\n");
            if (prop.getZoning() != null)       content.append("Zoning:        ").append(prop.getZoning()).append("\n");
            if (prop.getMarketValue() != null)  content.append(String.format("Market Value:  Rs %,.0f%n", prop.getMarketValue()));
            content.append("\nVerified: ").append(Boolean.TRUE.equals(prop.getVerified()) ? "Yes" : "No").append("\n");
        }

        return section(report, "PROPERTY_OVERVIEW", "Property Overview", order,
                content.toString(), toJson(prop));
    }

    // ── RISK_ANALYSIS ─────────────────────────────────────────────

    private ReportSection buildRiskAnalysis(DueDiligenceReport report,
                                            RiskBreakdownDto breakdown, int order) {
        StringBuilder content = new StringBuilder();
        content.append("Risk Analysis\n");
        content.append("=============\n\n");
        content.append("Overall Score: ")
                .append(String.format("%.1f", breakdown.getOverallScore()))
                .append(" / 100 — ").append(breakdown.getOverallLevel().name()).append("\n\n");
        content.append("Detailed factor analysis (ordered by risk contribution):\n\n");

        if (breakdown.getFactors() != null) {
            breakdown.getFactors().forEach(factor -> {
                content.append("> ").append(factor.getCategory().name())
                        .append(" — Score: ").append(String.format("%.1f", factor.getScore()))
                        .append(" (").append(factor.getLevel().name()).append(")")
                        .append(" — Weight: ").append(String.format("%.0f%%", factor.getWeight() * 100))
                        .append("\n");
                content.append("  Data Source: ").append(nvl(factor.getDataSource())).append("\n");
                content.append("  Analysis: ").append(nvl(factor.getExplanation())).append("\n");
                content.append("  Recommendation: ").append(nvl(factor.getRecommendation())).append("\n\n");
            });
        }

        return section(report, "RISK_ANALYSIS", "Risk Analysis", order,
                content.toString(), toJson(breakdown));
    }

    // ── COMPARABLE (placeholder) ──────────────────────────────────

    private ReportSection buildComparable(DueDiligenceReport report, int order) {
        String content = """
                Comparable Property Analysis
                ============================

                Comparable property analysis will be included in a future report version.
                This section will feature:
                  * Recent sales of similar properties within 2 km
                  * Price per sq. ft. benchmarking
                  * Market trend analysis (12-month rolling average)
                  * Valuation confidence band

                (This module is under active development.)
                """;
        return section(report, "COMPARABLE", "Comparable Property Analysis", order, content, null);
    }

    // ── FINANCIAL ─────────────────────────────────────────────────

    private ReportSection buildFinancial(DueDiligenceReport report,
                                         AggregatedPropertyResponse agg, int order) {
        var prop = agg.getProperty();
        StringBuilder content = new StringBuilder();
        content.append("Financial Analysis\n");
        content.append("==================\n\n");

        if (prop != null && prop.getMarketValue() != null) {
            content.append(String.format("Declared Market Value: Rs %,.0f%n", prop.getMarketValue()));
            if (prop.getArea() != null && prop.getArea() > 0) {
                content.append(String.format("Price per sq. ft.:     Rs %,.0f%n",
                        prop.getMarketValue() / prop.getArea()));
            }
        } else {
            content.append("Market value not recorded — valuation analysis unavailable.\n");
        }

        content.append("\n--- Tax Records ---\n");
        var taxResp = agg.getTaxHistory();
        if (taxResp != null && taxResp.getData() != null && !taxResp.getData().isEmpty()) {
            var records = taxResp.getData();
            content.append("Tax records available: ").append(records.size()).append("\n");
            long paid = records.stream().filter(r -> "PAID".equalsIgnoreCase(r.getStatus())).count();
            long overdue = records.stream().filter(r -> "OVERDUE".equalsIgnoreCase(r.getStatus())).count();
            long pending = records.stream().filter(r -> "PENDING".equalsIgnoreCase(r.getStatus())).count();
            content.append(String.format("  Paid:    %d%n", paid));
            content.append(String.format("  Pending: %d%n", pending));
            content.append(String.format("  Overdue: %d%n", overdue));
            if (overdue > 0) {
                content.append("\nWarning: ").append(overdue)
                        .append(" overdue tax record(s) may become a lien on the property.\n");
            }
        } else {
            content.append("No tax records available.\n");
        }

        content.append("\n--- Ownership & Stamp Duty ---\n");
        var ownershipResp = agg.getOwnership();
        if (ownershipResp != null && ownershipResp.getData() != null) {
            var record = ownershipResp.getData();
            if (record.getRegisteredValue() != null) {
                content.append(String.format("Registered Value:  Rs %,.0f%n", record.getRegisteredValue()));
            }
            if (record.getStampDutyPaid() != null) {
                content.append(String.format("Stamp Duty Paid:   Rs %,.0f%n", record.getStampDutyPaid()));
            }
        } else {
            content.append("Ownership records unavailable — financial verification incomplete.\n");
        }

        return section(report, "FINANCIAL", "Financial Analysis", order,
                content.toString(), toJson(agg));
    }

    // ── RECOMMENDATIONS ───────────────────────────────────────────

    private ReportSection buildRecommendations(DueDiligenceReport report,
                                               RiskBreakdownDto breakdown, int order) {
        StringBuilder content = new StringBuilder();
        content.append("Recommendations\n");
        content.append("===============\n\n");
        content.append("Prioritized action items based on identified risks:\n\n");

        int step = 1;
        if (breakdown.getFactors() != null) {
            for (var factor : breakdown.getFactors()) {
                if (factor.getScore() < 25) continue;
                content.append(step++).append(". [").append(factor.getCategory().name()).append("] ")
                        .append(nvl(factor.getRecommendation())).append("\n\n");
            }
        }

        if (step == 1) {
            content.append("No high-priority recommendations — property risk is within acceptable range. ")
                    .append("Standard due diligence checks are still advised before any transaction.\n");
        }

        content.append("\n-----------------------------------------------------------\n");
        content.append("General Guidance\n");
        content.append("-----------------------------------------------------------\n");
        content.append("* Always engage a qualified property lawyer for legal review.\n");
        content.append("* Obtain an official encumbrance certificate from Sub-Registrar office.\n");
        content.append("* Verify property tax clearance with the local municipal body.\n");
        content.append("* Conduct a physical inspection with a certified surveyor.\n");
        content.append("* Cross-verify all documentation with original records at government offices.\n");

        return section(report, "RECOMMENDATIONS", "Recommendations", order,
                content.toString(),
                toJson(breakdown.getFactors()));
    }

    // ── APPENDIX ──────────────────────────────────────────────────

    private ReportSection buildAppendix(DueDiligenceReport report,
                                        AggregatedPropertyResponse agg, int order) {
        StringBuilder content = new StringBuilder();
        content.append("Appendix — Data Sources & Methodology\n");
        content.append("=====================================\n\n");
        content.append("Data Sources Used:\n");
        appendSourceStatus(content, "Ownership",     agg.getOwnership());
        appendSourceStatus(content, "Tax History",   agg.getTaxHistory());
        appendSourceStatus(content, "Zoning",        agg.getZoning());
        appendSourceStatus(content, "Flood Zone",    agg.getFloodZone());
        appendSourceStatus(content, "Permits",       agg.getPermits());
        appendSourceStatus(content, "Environmental", agg.getEnvironmental());
        content.append("\nOverall Aggregation Status: ")
                .append(agg.getOverallStatus() != null ? agg.getOverallStatus().name() : "UNKNOWN")
                .append("\n");
        if (agg.getTotalDurationMs() != null) {
            content.append("Data fetch duration: ").append(agg.getTotalDurationMs()).append("ms\n");
        }

        content.append("\n-----------------------------------------------------------\n");
        content.append("Risk Scoring Methodology\n");
        content.append("-----------------------------------------------------------\n");
        content.append("This report uses a weighted composite risk score (0-100).\n\n");
        content.append("Category Weights:\n");
        content.append("  * Flood:         25%\n");
        content.append("  * Legal:         20%\n");
        content.append("  * Tax:           15%\n");
        content.append("  * Zoning:        15%\n");
        content.append("  * Environmental: 15%\n");
        content.append("  * Market:        10%\n\n");
        content.append("Risk Levels:\n");
        content.append("  * LOW:      0-25\n");
        content.append("  * MEDIUM:   26-50\n");
        content.append("  * HIGH:     51-75\n");
        content.append("  * CRITICAL: 76-100\n\n");
        content.append("When data sources are unavailable, an uncertainty penalty is applied ")
                .append("to that category rather than assuming zero risk — this reflects that ")
                .append("missing information is itself a risk factor.\n\n");

        content.append("-----------------------------------------------------------\n");
        content.append("Disclaimer\n");
        content.append("-----------------------------------------------------------\n");
        content.append("This report is generated from third-party data sources and property records. ")
                .append("It is provided for informational purposes only and does not constitute legal, ")
                .append("financial, or investment advice. Always consult qualified professionals before ")
                .append("making a property transaction decision.\n");

        return section(report, "APPENDIX", "Appendix", order, content.toString(), null);
    }

    // ── HELPERS ───────────────────────────────────────────────────

    private void appendSourceStatus(StringBuilder sb, String label, IntegrationResponse<?> resp) {
        sb.append("  * ").append(label).append(": ");
        if (resp == null) {
            sb.append("Not available\n");
            return;
        }
        sb.append(resp.getStatus() != null ? resp.getStatus().name() : "UNKNOWN");
        if (resp.getDataSource() != null) sb.append(" — ").append(resp.getDataSource());
        sb.append("\n");
    }

    private ReportSection section(DueDiligenceReport report, String type, String title,
                                  int order, String content, String dataJson) {
        return ReportSection.builder()
                .report(report)
                .sectionType(type)
                .title(title)
                .orderIndex(order)
                .content(content)
                .dataJson(dataJson)
                .build();
    }

    private String toJson(Object value) {
        if (value == null) return null;
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            log.warn("Failed to serialize report section data: {}", e.getMessage());
            return null;
        }
    }

    private String nvl(String s) { return s != null ? s : ""; }
    private double nvl(Double v) { return v != null ? v : 0.0; }

    private String levelForScore(Double s) {
        if (s == null) return "UNKNOWN";
        if (s < 26) return "LOW";
        if (s < 51) return "MEDIUM";
        if (s < 76) return "HIGH";
        return "CRITICAL";
    }
}