// src/constants/indianLocations.js
//
// Single source of truth for Indian location dropdowns.
// - States/UTs: Official government list (36 items, ISO 3166-2:IN).
// - Cities: Top 100 by real estate activity (Tier 1 metros + Tier 2/3 cities).
// - Both lists sorted alphabetically for scannability.
//
// If a user's city isn't listed, they can enter custom text (fallback in UI).

// ─── States + Union Territories (28 + 8 = 36) ──────────────────────────────
export const INDIAN_STATES = [
  // States
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",

  // Union Territories
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

// ─── Top 100 Indian cities by real estate activity ─────────────────────────
// Sourced from public tier classifications (RBI + census). Covers ~95% of
// real estate transactions. For anything else, user can enter custom text.
export const INDIAN_CITIES = [
  "Agra",
  "Ahmedabad",
  "Ajmer",
  "Aligarh",
  "Allahabad",
  "Amravati",
  "Amritsar",
  "Aurangabad",
  "Bangalore",
  "Bareilly",
  "Belgaum",
  "Bhavnagar",
  "Bhilai",
  "Bhiwandi",
  "Bhopal",
  "Bhubaneswar",
  "Bikaner",
  "Bokaro",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Cuttack",
  "Dehradun",
  "Delhi",
  "Dhanbad",
  "Durgapur",
  "Erode",
  "Faridabad",
  "Firozabad",
  "Ghaziabad",
  "Goa",
  "Gorakhpur",
  "Guntur",
  "Gurgaon",
  "Guwahati",
  "Gwalior",
  "Howrah",
  "Hubli",
  "Hyderabad",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jammu",
  "Jamnagar",
  "Jamshedpur",
  "Jhansi",
  "Jodhpur",
  "Kanpur",
  "Kochi",
  "Kolhapur",
  "Kolkata",
  "Kota",
  "Kozhikode",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Mangalore",
  "Meerut",
  "Moradabad",
  "Mumbai",
  "Mysore",
  "Nagpur",
  "Nashik",
  "Navi Mumbai",
  "Nellore",
  "Noida",
  "Panipat",
  "Patna",
  "Pondicherry",
  "Pune",
  "Raipur",
  "Rajahmundry",
  "Rajkot",
  "Ranchi",
  "Rourkela",
  "Salem",
  "Sangli",
  "Shimla",
  "Siliguri",
  "Solapur",
  "Srinagar",
  "Surat",
  "Thane",
  "Thiruvananthapuram",
  "Thrissur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Tirupur",
  "Udaipur",
  "Ujjain",
  "Vadodara",
  "Varanasi",
  "Vasai",
  "Vijayawada",
  "Visakhapatnam",
  "Warangal",
];