spring.application.name=due-diligence-agent

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/real_estate_due_diligence
spring.datasource.username=postgres
spring.datasource.password=Akshay5764.@

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=ThisIsMySuperSecretKeyForDueDiligenceProject2026SpringBootJWTAuthentication
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
server.port=8080