// backend/src/main/java/com/realestate/duediligence/dto/RiskAssessmentResponse.java
package com.realestate.duediligence.dto;

import java.time.Instant;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.realestate.duediligence.enums.RiskLevel;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Summary risk response — used by GET /api/properties/{propertyId}/risk
 *
 * Lighter than RiskBreakdownDto: no factor explanations, just scores
 * and the summary text. Designed for property cards and overview panels.
 *
 * For full explainability, use /risk/breakdown endpoint.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class RiskAssessmentResponse {

    private Long assessmentId;
    private Long propertyId;

    /** Overall weighted risk score 0–100. Higher = more risk. */
    private double overallScore;

    /** LOW / MEDIUM / HIGH / CRITICAL */
    private RiskLevel overallLevel;

    // ── Category scores (0–100 each, no explanations here) ───────

    private double floodScore;
    private double legalScore;
    private double taxScore;
    private double zoningScore;
    private double environmentalScore;
    private double marketScore;

    /**
     * 2–3 sentence executive summary generated by the engine.
     * Example: "This property carries HIGH overall risk driven primarily
     * by its FLOOD_PRONE zone classification and 2 overdue tax records.
     * Immediate review of flood insurance and tax clearance is advised."
     */
    private String summary;

    /**
     * True if the score was freshly computed (not from cache/DB).
     * Frontend can show "Just calculated" vs "Calculated 3 hours ago".
     */
    private boolean freshlyComputed;

    /**
     * True if any data source was MOCK/UNAVAILABLE.
     * Frontend shows a subtle data quality indicator.
     */
    private boolean dataIncomplete;

    /** When this assessment was originally calculated. */
    private Instant calculatedAt;

    /**
     * Version number — increments on each recalculate.
     * Not exposed to regular UI but useful for history tracking.
     */
    private int version;
}